dimensionality_reduction:
  autoencoder:
    input_dim: ${model.dimensionality_reduction.autoencoder.input_dim}
    encoding_dim: ${model.dimensionality_reduction.autoencoder.encoding_dim}
    hidden_layers: ${model.dimensionality_reduction.autoencoder.hidden_layers}
    activation: ${model.dimensionality_reduction.autoencoder.activation}
    batch_size: ${model.dimensionality_reduction.autoencoder.batch_size}
    epochs: ${model.dimensionality_reduction.autoencoder.epochs}
    learning_rate: ${model.dimensionality_reduction.autoencoder.learning_rate}
prediction:
  lstm_ae:
    sequence_length: ${model.prediction.lstm_ae.sequence_length}
    hidden_size: ${model.prediction.lstm_ae.hidden_size}
    num_layers: ${model.prediction.lstm_ae.num_layers}
    dropout: ${model.prediction.lstm_ae.dropout}
    batch_size: ${model.prediction.lstm_ae.batch_size}
    epochs: ${model.prediction.lstm_ae.epochs}
    learning_rate: ${model.prediction.lstm_ae.learning_rate}
    patience: ${model.prediction.lstm_ae.patience}
    input_sources:
      use_salinity: ${model.prediction.lstm_ae.input_sources.use_salinity}
      use_wind: ${model.prediction.lstm_ae.input_sources.use_wind}
      use_flow: ${model.prediction.lstm_ae.input_sources.use_flow}
