# conf/training/default.yaml



random_seed: 42
# --- 数据集配置 ---
# --- 数据分割参数 ---
spilt_group: ['train', 'val', 'test']
validation_split: 0.2
test_split: 0.1  # 预留用于最终测试的数据比例

# 重采样
wind_compression : 20  # 风速压缩比例
flow_boradcast:   600 # 流量预报比例
# --- 特征配置 ---
use_scaler: true  # 是否使用标准化

# --- 训练参数 ---
batch_size: 64
epochs: 100
early_stopping:
  enabled: true
  patience: 10
  min_delta: 1.0e-4

# --- SOM训练参数 ---
som:
  map_size_sta : [3,3]
  map_size: [3,3] # 提供sal的地图尺寸
  map_size_obs : [3,3] # 提供obs的地图尺寸
  learning_rate: 0.1
  n_iterations: 100
  neighborhood_size: null
  sigma: 1.25

training:
  # --- 添加 optimizer 部分 ---
  optimizer:
    name: Adam     # 优化器名称 (例如 Adam, SGD)
    learning_rate: 0.001 # 学习率
    weight_decay: 0.0001 # (可选) 权重衰减
    betas: [0.9, 0.999]  # (可选) Adam 的 beta 参数
    # ... 其他优化器特定参数 ...

  # --- 其他训练参数 ---
  epochs: 50          # 训练轮数 (根据需要调整)
  # batch_size: 32      # Batch size (可能在 lstm 配置下更合适，检查 train_lstm.py)
  # early_stopping_patience: 10 # (可选) 早停耐心值
  # ...

# --- 日志配置 ---
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  to_file: true
  filename: "training.log"